#!/bin/bash

BIN_PATH=/cad2/ece344f/cs161/bin
TEST_PATH=/cad2/ece344f/os161-tester

# Set up the TEST_PATH for a non-install location.
BIN_PATH_CANON=$(readlink -f $BIN_PATH)
CUR_PATH_CANON=$(dirname $(readlink -f $BASH_SOURCE))
if [ $BIN_PATH_CANON != $CUR_PATH_CANON ]; then
    TEST_PATH=$CUR_PATH_CANON
    echo "Tester path is $TEST_PATH"
fi

#setup the path, making sure that our path is first
export PATH=$BIN_PATH:$PATH

PROG=$(basename $0)

function usage() {
    echo "Usage: $PROG [-hvV] [assignment_nr]" 1>&2;
    echo "           -h: show this message" 1>&2;
    echo "           -v: verbose" 1>&2;
    echo "           -V: very verbose" 1>&2;
    echo "assignment_nr: If not specified, then all tests are run" 1>&2
    echo "               Otherwise, it must be 0, 1, 2 or 3" 1>&2;
    exit 1;
}

# make sure that we are in the correct OS161 root directory
if [ ! -f kernel ]; then
    echo "$PROG: The os161 kernel executable does not exist in this directory. Run this script from the OS161 root directory." 1>&2;
    exit 1;
fi

if [ ! -x kernel ]; then
    echo "$PROG: The os161 kernel executable in this directory is not executable. Run this script from the OS161 root directory." 1>&2;
    exit 1;
fi

# getopts processing
while getopts "vhV" ARG ; do
    if [ ${ARG} = 'v' ]; then
        if [ -z "$VERBOSE" ]; then
            VERBOSE=1;
        fi
    elif [ ${ARG} = 'V' ]; then
        VERBOSE=2
    elif [ ${ARG} = 'h' ]; then
        usage;
    else
        usage;
    fi
done

export OS161_TESTER_VERBOSE=$VERBOSE

shift $((OPTIND-1))

# by default, check all assignments
ASSIGNMENTS="0 1 2 3"

if [ $# -gt 1 ]; then
    usage;
fi

if [ $# -eq 1 ]; then
    if [ $1 != "0" -a $1 != "1" -a $1 != "2" -a $1 != "3" ]; then
        usage;
    fi
    # check only one assignment
    ASSIGNMENTS=$1
fi

for i in $ASSIGNMENTS; do
    echo "Running tests for Assignment $i";
    for test in $TEST_PATH/core/asst${i}*.py; do
        if [ -x $test ]; then
            echo "Running: $test kernel";
            $test kernel;
        fi
    done
    echo
done

