#!/bin/bash

TESTER_PATH=$(dirname $(readlink -f $BASH_SOURCE))
. $TESTER_PATH/../bin/setup

function usage() {
    echo "Usage: $PROG [-h] [-s start] [-e end] asst_nr" 1>&2;
    echo "       $PROG -b filename path" 1>&2;
    echo "        -h: show this message" 1>&2;
    echo "  -s start: run marker starting from group 'start'" 1>&2;
    echo "    -e end: run marker until group 'end'" 1>&2;
    echo "   asst_nr: run test on lab number" 1>&2
    echo "            must be 1, 2 or 3" 1>&2;
    echo "        -b: generate base file" 1>&2;
    echo "  filename: file name of the base file" 1>&2;
    echo "      path: absolute path to base directory" 1>&2;
    exit 1;
}

# getopts processing
while getopts "hs:e:b:" ARG ; do
    if [ ${ARG} = 's' ]; then
        START=$OPTARG;
        if ! [[ "$START" =~ ^[0-9]+$ ]] ; then
            usage;
        fi
    elif [ ${ARG} = 'e' ]; then
        END=$OPTARG;
        if ! [[ "$END" =~ ^[0-9]+$ ]] ; then
            usage;
        fi
    elif [ ${ARG} = 'b' ]; then
        BASEFILE=$OPTARG;
    elif [ ${ARG} = 'h' ]; then
        usage;
    else
        usage;
    fi
done

shift $((OPTIND-1))

if [ $# -ne 1 ]; then
    usage;
fi

function add_header() {
	echo "" >> $2
	echo "//----------------------------------------------------------------" \
	>> $2
	echo "// $1" >> $2
	echo "//----------------------------------------------------------------" \
	>> $2
	echo "" >> $2
}

if [ -n "$BASEFILE" ]; then
	cat /dev/null > $BASEFILE
	find $1 -name [^.]*.c -o -name [^.]*.h | while read -r F; do
		RF=`echo $F | sed "s|$1/*||"`
		add_header $RF $BASEFILE
		cat $F >> $BASEFILE
	done
	exit 0
fi

if [ $1 != "1" -a $1 != "2" -a $1 != "3" ]; then
    usage;
fi

NR=$1
SVN_ROOT=svn+ssh://ug250.eecg.utoronto.ca/svn
SVN_BEFORE=svn/tags/asst$((NR-1))-end/kern
SVN_AFTER=svn/tags/asst$NR-end/kern

for GROUP_NUM in $(seq -f "%03g" ${START} ${END}); do
	GROUP=os-$GROUP_NUM
	FILE=$GROUP.cc
	cat /dev/null > touch $FILE
	svn diff --diff-cmd diff -x -uwq $SVN_ROOT/$GROUP/$SVN_BEFORE \
	$SVN_ROOT/$GROUP/$SVN_AFTER | grep "^Index: " | awk '{ print $2 }' | \
	while read -r F; do
		if [[ "$F" =~ .*\.[c|h]$ ]]; then
			add_header $F $FILE
			svn cat $SVN_ROOT/$GROUP/$SVN_AFTER/$F >> $FILE
		else
			echo "$F" >> $GROUP-ignore.txt
		fi
	done
done

