#!/bin/bash

TESTER_PATH=$(dirname $(readlink -f $BASH_SOURCE))
. $TESTER_PATH/../bin/setup

PROG=$(basename $0)

function usage() {
    echo "Usage: $PROG [-h] [-s start] [-e end] asst_nr" 1>&2;
    echo "        -h: show this message" 1>&2;
    echo "  -s start: run marker starting from group 'start'" 1>&2;
    echo "    -e end: run marker until group 'end'" 1>&2;
    echo "   asst_nr: run test on lab number" 1>&2
    echo "            must be 1, 2 or 3" 1>&2;
    exit 1;
}

# getopts processing
while getopts "hs:e:" ARG ; do
    if [ ${ARG} = 's' ]; then
        START=$OPTARG;
        if ! [[ "$START" =~ ^[0-9]+$ ]] ; then
            usage;
        fi
    elif [ ${ARG} = 'e' ]; then
        END=$OPTARG;
        if ! [[ "$END" =~ ^[0-9]+$ ]] ; then
            usage;
        fi
    elif [ ${ARG} = 'h' ]; then
        usage;
    else
        usage;
    fi
done

shift $((OPTIND-1))

if [ $# -ne 1 ]; then
    usage;
fi

if [ $1 != "1" -a $1 != "2" -a $1 != "3" ]; then
    usage;
fi

function add_header() {
	echo "" >> $2
	echo "//----------------------------------------------------------------" >> $2
	echo "// $1" >> $2
	echo "" >> $2
	echo "" >> $2
}

NR=$1

PREV=asst$((NR-1))
CURR=asst$NR
AFTER=$INSTALL_PATH/results/$CURR/source

for GROUP_NUM in $(seq -f "%03g" ${START} ${END}); do
	GROUP=os-$GROUP_NUM
	FILE=$GROUP.txt
        rm -f $FILE
        touch $FILE

        find $AFTER/$GROUP -name "*".[ch] | sort | \
	while read -r FN; do
                FO=${FN/$CURR/$PREV}
                if [ -f $FN -a -f $FO ]; then
                        cmp $FO $FN > /dev/null
                        if [ $? -eq 0 ]; then
                                continue;
                        fi
                fi
                add_header $FN $FILE
                diff -w -N $FN $FO >> $FILE
        done
done

exit 0

