#!/bin/bash

TESTER_PATH=$(dirname $(readlink -f $BASH_SOURCE))
. $TESTER_PATH/../bin/setup

PROG=$(basename $0)

function usage() {
    echo "Usage: $PROG [-h] newdir olddir output-file" 1>&2;
    echo "        -h: show this message" 1>&2;
    echo "   diff newdir with olddir and put the difference in output-file" 1>&2
    exit 1;
}

if [ $# -lt 3 ]; then
    usage;
fi

NEWDIR=$1
OLDDIR=$2
FILE=$3

echo $OLDDIR 1>&2
echo $NEWDIR 1>&2

find $NEWDIR -name "*".[ch] | sort | \
        while read -r FN; do
        FO=${FN/$NEWDIR/$OLDDIR}
        echo $FN, $FO 1>&2
        if [ -f $FN -a -f $FO ]; then
                cmp $FO $FN > /dev/null
                if [ $? -eq 0 ]; then
                        continue;
                fi
        fi
        diff --strip-trailing -u -w -N $FN $FO >> $FILE
done

exit 0